server:
    port: ${SERVER_PORT}  # 환경 변수로 대체

spring:
    application:
        name: newscrab

    config:
        import: optional:file:.env[.properties]

    web:
        encoding:
            charset: UTF-8
            enabled: true
            force: true

    datasource:
        url: jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/${MYSQL_DATABASE}?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8&serverTimezone=UTC
        username: ${MYSQL_ROOT_USER}  # 환경 변수로 대체
        password: ${MYSQL_ROOT_PASSWORD}  # 환경 변수로 대체
        driver-class-name: com.mysql.cj.jdbc.Driver

    jpa:
        properties:
            hibernate:
                show_sql: false
                format_sql: false
        hibernate:
            ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO}
            database-platform: org.hibernate.dialect.MySQLDialect

    logging:
        level:
            com.gihojise.newscrab.interceptor.LoggingInterceptor: INFO

    data:
        redis:
            host: ${REDIS_HOST}  # 환경 변수로 대체
            port: ${REDIS_PORT}  # 환경 변수로 대체
            password: ${REDIS_PASSWORD}  # 환경 변수로 대체

    jwt:
        secret: ${JWT_SECRET}  # 환경 변수로 대체

# Swagger Configuration
springdoc:
    api-docs:
        enabled: true
    swagger-ui:
        enabled: true
        path: /swagger-ui.html
